name: events Demo 1
on:
    pull_request:
        types: 
          - opened #activity type
        branches:
          - main
          - 'dev-*' # dev-new dev-this-is-new
          - 'feat/**' #feat/new feat/new/button
    workflow_dispatch:
    push:
      branches:
        - main
        - 'dev-*' # dev-new dev-this-is-new  filter activity
        - 'feat/**' #feat/new feat/new/button
      paths-ignore:
        - '.github/workflows/*'
jobs:
    codequality:
        runs-on: ubuntu-latest
        steps:
        - name: Output event data
          run: echo "${{toJSON(github.event)}}"
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: launch lint code quality
          run: npm run lint
        - name: launch tests
          run: npm run test
        - name: launch deploy
          run: echo "Deploying......."