name: deploy app react
on: push
jobs:
    codequality:
        runs-on: ubuntu-latest
        steps:
        - name: launch lint code quality
          run: npm lint
    test:
        runs-on: ubuntu-latest
        needs: codequality
        steps:
        - name: launch tests
          run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - name: launch deploy
          run: echo "Deploying......."