name: deploy app react
on: workflow_dispatch
jobs:
    codequality:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install nodeJs
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: launch lint code quality
          run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: codequality
        steps:
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install nodeJs
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci   
        - name: launch tests
          run: npm run test

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - name: launch deploy
          run: echo "Deploying......."