name: issues workflow
on:
    issues:
      types:
        - opened
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
        - name: print
          run: echo "${{ toJSON(github.event)}}"
#add