name: Circle Workflow

#   issue_comment:  
#     types: [created]
#   issues:
#     types: [opened, closed] 
on:
    pull_request:
      types: [opened]
      branches:
        - master


jobs:
  circle-workflow:
    name: ${{ github.event_name }}-${{ github.event.action }} workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: your-new-branch-name
        
    # - name: Setup Git
    #   run: git config --global --add safe.directory /github/workspaceee
    - name: Replace config
      run: cp .circleci/${{ github.event_name }}-${{ github.event.action }}.yml .circleci/config.yml
    - name: commit-push_branch-test
      uses: dsayling/commit-branch-check-action@v0.1.5
      with:
        github-token: ${{ secrets.TOKEN }}
        commit-message: "Run workflow"
        dest-branch: ${{ github.event_name }}-${{ github.event.action }}
        verify-checks: false
        delete-after-checks: true